// Research pass across all 50 state high school athletic/activities
// associations: official name, handbook/bulletins URLs, and eligibility
// contact info, gathered from each association's own public site.
//
// IMPORTANT — read before relying on this in production:
// - Several official sites blocked automated fetching (403s) during
//   research; those entries are sourced from search-indexed snippets of the
//   same official pages rather than a direct page read. Check `notes`.
// - Any field we could not verify against an official page is `null` —
//   we did not guess or fabricate contact details.
// - Iowa is a special case: boys' athletics are governed by IHSAA
//   (iahsaa.org, used below), girls' athletics by the separate Iowa Girls
//   High School Athletic Union (IGHSAU, ighsau.org) — this dataset only
//   covers IHSAA. Add a second Iowa-girls record if the app needs to
//   distinguish them.
// - California (CIF) is decentralized into 10 geographic Sections, each
//   with its own bylaws layered on top of state bylaws and its own
//   eligibility office. The record below is the state office only.
// - Before this goes live for a given state, a human should sanity-check
//   the contact info against the association's current site — associations
//   reorganize staff and swap handbook URLs between seasons.

export interface StateConfigResearch {
  state_code: string;
  state_name: string;
  association_name: string;
  handbook_url: string;
  bulletins_url: string | null;
  level?: "high_school" | "college"; // defaults to high_school when omitted
  eligibility_contact_name: string | null;
  eligibility_contact_phone: string | null;
  eligibility_contact_email: string | null;
  notes: string;
}

export const STATE_CONFIG_DATA: StateConfigResearch[] = [
  {
    state_code: "al",
    state_name: "Alabama",
    association_name: "Alabama High School Athletic Association (AHSAA)",
    handbook_url: "https://www.ahsaa.com/Portals/0/Publications/2026-2027/J011687%20Handbookweb.pdf",
    bulletins_url: "https://www.ahsaa.com/School-Parent-Resources/AHSAA/About-Us/Central-Board-Legislative-Council",
    eligibility_contact_name: "AHSAA Office",
    eligibility_contact_phone: "(334) 263-6994",
    eligibility_contact_email: null,
    notes: "No single dedicated eligibility email published. Central Board minutes (which include bylaw amendments) are posted under About Us > Central Board/Legislative Council.",
  },
  {
    state_code: "ak",
    state_name: "Alaska",
    association_name: "Alaska School Activities Association (ASAA)",
    handbook_url: "https://asaa.org/resources/sports-medicine/bylaws-and-policies/",
    bulletins_url: null,
    eligibility_contact_name: "ASAA Executive Director",
    eligibility_contact_phone: "(907) 563-3723",
    eligibility_contact_email: "billy@asaa.org",
    notes: "Small association, no separate bulletins page — updates posted directly on the Bylaws and Policies page.",
  },
  {
    state_code: "az",
    state_name: "Arizona",
    association_name: "Arizona Interscholastic Association (AIA)",
    handbook_url: "https://aiaonline.org/about/constitution-bylaws",
    bulletins_url: null,
    eligibility_contact_name: "Nathan Slater, Associate Executive Director (Hardships/Eligibility)",
    eligibility_contact_phone: "(602) 385-3811",
    eligibility_contact_email: "nslater@aiaonline.org",
    notes: "AIA splits eligibility/hardship handling by sport between two Associate Executive Directors; Toni Corona (tcorona@aiaonline.org, (602) 385-3821) covers the other half.",
  },
  {
    state_code: "ar",
    state_name: "Arkansas",
    association_name: "Arkansas Activities Association (AAA)",
    handbook_url: "https://cdn1.sportngin.com/attachments/document/fba9-3476214/2025-2026__AAA_Handbook.pdf",
    bulletins_url: "https://www.ahsaa.org/documents",
    eligibility_contact_name: "AAA Office",
    eligibility_contact_phone: "(501) 955-2500",
    eligibility_contact_email: null,
    notes: "Official domain is ahsaa.org (not to be confused with Alabama's AHSAA). No verified email found.",
  },
  {
    state_code: "ca",
    state_name: "California",
    association_name: "California Interscholastic Federation (CIF)",
    handbook_url: "https://www.cifstate.org/governance/constitution/index",
    bulletins_url: "https://www.cifstate.org/governance/fed_council/agendas_minutes/index",
    eligibility_contact_name: "CIF State Office",
    eligibility_contact_phone: "(916) 239-4477",
    eligibility_contact_email: null,
    notes: "CIF is decentralized into 10 geographic Sections, each with its own bylaws layered on the state constitution and its own eligibility office — this is the state office only. Confirm which Section governs a given school.",
  },
  {
    state_code: "co",
    state_name: "Colorado",
    association_name: "Colorado High School Activities Association (CHSAA)",
    handbook_url: "https://chsaanow.com/sports/2021/7/19/bylaws.aspx",
    bulletins_url: null,
    eligibility_contact_name: "CHSAA Office",
    eligibility_contact_phone: "(303) 344-5050",
    eligibility_contact_email: null,
    notes: "Corrects the seed placeholder: phone confirmed correct, but 'eligibility@chsaa.org' does not exist — CHSAA staff use individual firstinitiallastname@chsaa.org addresses with no published consolidated eligibility inbox.",
  },
  {
    state_code: "ct",
    state_name: "Connecticut",
    association_name: "Connecticut Interscholastic Athletic Conference (CIAC), a division of the Connecticut Association of Schools (CAS)",
    handbook_url: "https://www.casciac.org/pdfs/ciachandbook_2324.pdf",
    bulletins_url: "https://www.casciac.org/pdfs/Approved_CIAC_Bylaw_Changes_2025.pdf",
    eligibility_contact_name: "CAS-CIAC Office",
    eligibility_contact_phone: "(203) 250-1111",
    eligibility_contact_email: null,
    notes: "Newest single-file handbook PDF located dates to 2023-24; a 2025 bylaw-changes document from the CAS Annual Meeting is the best available amendments source — verify a newer handbook edition exists before relying on this link.",
  },
  {
    state_code: "de",
    state_name: "Delaware",
    association_name: "Delaware Interscholastic Athletic Association (DIAA)",
    handbook_url: "https://education.delaware.gov/diaa/diaa_for/athletic-directors/official_handbook/",
    bulletins_url: null,
    eligibility_contact_name: "DIAA Office",
    eligibility_contact_phone: "(302) 857-3365",
    eligibility_contact_email: "diaa@doe.k12.de.us",
    notes: "DIAA operates as a division of the Delaware Dept of Education, not an independent nonprofit — rules are DOE regulations.",
  },
  {
    state_code: "fl",
    state_name: "Florida",
    association_name: "Florida High School Athletic Association (FHSAA)",
    handbook_url: "https://s3.amazonaws.com/fhsaa.org/documents/2024/11/20/2425_handbook_update_11424.pdf",
    bulletins_url: "https://fhsaa.com/sports/2020/1/28/RulesPub.aspx",
    eligibility_contact_name: "Stephanie Shafer, Administrator of Eligibility & Compliance",
    eligibility_contact_phone: "(352) 372-9551",
    eligibility_contact_email: "sshafer@fhsaa.org",
    notes: "FHSAA has multiple eligibility/compliance administrators assigned by region/sport (Moseley, Pollock, Shafer, Shannon) under Associate Executive Director Jordanne Stark-Miller — confirm which one covers a given region/sport.",
  },
  {
    state_code: "ga",
    state_name: "Georgia",
    association_name: "Georgia High School Association (GHSA)",
    handbook_url: "https://www.ghsa.net/constitution-2025-2026-ghsa-constitution-and-by-laws",
    bulletins_url: null,
    eligibility_contact_name: "Carror Wright, Associate Director (Student Eligibility & Investigations)",
    eligibility_contact_phone: "(706) 647-7473",
    eligibility_contact_email: "cwright@ghsa.net",
    notes: "Executive Director Dr. James R. Hines Jr. (robin.hines@ghsa.net) is a secondary contact for rule interpretation and hardship appeals.",
  },
  {
    state_code: "hi",
    state_name: "Hawaii",
    association_name: "Hawaii High School Athletic Association (HHSAA)",
    handbook_url: "https://hhsaa.org/handbook",
    bulletins_url: null,
    eligibility_contact_name: "HHSAA Office",
    eligibility_contact_phone: "(808) 587-4495",
    eligibility_contact_email: "info@hhsaa.org",
    notes: "No dedicated eligibility-specific staff contact published separately.",
  },
  {
    state_code: "id",
    state_name: "Idaho",
    association_name: "Idaho High School Activities Association (IHSAA)",
    handbook_url: "https://idhsaa.org/rules",
    bulletins_url: null,
    eligibility_contact_name: "IHSAA Office",
    eligibility_contact_phone: "208-375-7027",
    eligibility_contact_email: null,
    notes: "Rules (including Rule 8 - Individual Eligibility) are published as individual PDFs rather than one bound handbook. Staff emails are obfuscated on the site.",
  },
  {
    state_code: "il",
    state_name: "Illinois",
    association_name: "Illinois High School Association (IHSA)",
    handbook_url: "https://www.ihsa.org/about/constitution-by-laws-policies",
    bulletins_url: "https://www.ihsa.org/NewsMedia/Announcements/BoardMeetingMinutes.aspx",
    eligibility_contact_name: "IHSA Office",
    eligibility_contact_phone: "(309) 663-6377",
    eligibility_contact_email: null,
    notes: "ihsa.org blocked automated fetching during research; contact details sourced from search-indexed pages, not a direct read. Staff emails are click-to-reveal on the site.",
  },
  {
    state_code: "in",
    state_name: "Indiana",
    association_name: "Indiana High School Athletic Association (IHSAA)",
    handbook_url: "https://www.ihsaa.org/sites/default/files/documents/2025-26%20By-Laws.pdf",
    bulletins_url: "https://www.ihsaa.org/About-IHSAA/Minutes",
    eligibility_contact_name: "IHSAA Office (routes to school AD/principal first)",
    eligibility_contact_phone: "317-846-6601",
    eligibility_contact_email: null,
    notes: "IHSAA's official guidance is to route eligibility questions to the local school AD/principal first. No public email; site uses a contact form instead.",
  },
  {
    state_code: "ia",
    state_name: "Iowa",
    association_name: "Iowa High School Athletic Association (IHSAA) — boys' athletics only; girls' athletics governed separately by the Iowa Girls High School Athletic Union (IGHSAU, ighsau.org)",
    handbook_url: "https://www.iahsaa.org/wp-content/uploads/2024/11/2024-25-IHSAA-Handbook-FINAL.pdf",
    bulletins_url: null,
    eligibility_contact_name: "IHSAA Office",
    eligibility_contact_phone: "(515) 432-2011",
    eligibility_contact_email: null,
    notes: "Iowa uniquely splits governance by sex — this record covers boys' athletics (IHSAA) only. Add a separate IGHSAU record for girls' athletics if needed. Handbook link is the 2024-25 edition found via search — verify current year on iahsaa.org.",
  },
  {
    state_code: "ks",
    state_name: "Kansas",
    association_name: "Kansas State High School Activities Association (KSHSAA)",
    handbook_url: "https://www.kshsaa.org/Publications/Handbook.pdf",
    bulletins_url: "https://kshsaa.org/Publications/Board/SeptemberEB-Minutes-2024.pdf",
    eligibility_contact_name: "KSHSAA Office",
    eligibility_contact_phone: "785-273-5329",
    eligibility_contact_email: "kshsaa@kshsaa.org",
    notes: "Executive Board minutes published as individual PDFs; linked one example. No dedicated eligibility-specific contact beyond the Executive Director's general portfolio.",
  },
  {
    state_code: "ky",
    state_name: "Kentucky",
    association_name: "Kentucky High School Athletic Association (KHSAA)",
    handbook_url: "https://www.education.ky.gov/districts/legal/Documents/Bylaws%202026_ADA.pdf",
    bulletins_url: "https://khsaa.org/general/",
    eligibility_contact_name: "KHSAA Office",
    eligibility_contact_phone: "859-299-5472",
    eligibility_contact_email: null,
    notes: "Bylaws PDF found is hosted on the KY Dept of Education site; KHSAA's own site also hosts a handbook/bylaws section — verify current link at khsaa.org/general/resources/. No general email published, contact page lists phone/fax/mail only.",
  },
  {
    state_code: "la",
    state_name: "Louisiana",
    association_name: "Louisiana High School Athletic Association (LHSAA)",
    handbook_url: "https://www.lhsaa.org/about",
    bulletins_url: "https://www.lhsaa.org/siteuploads/lhsaa/1446_pdf_2025-26-basketball-general-bulletin.pdf",
    eligibility_contact_name: "Renee Ballard, Director of Online Eligibility & Compliance",
    eligibility_contact_phone: "225-296-5882 ext. 4214",
    eligibility_contact_email: "rballard@lhsaa.org",
    notes: "Handbook is distributed as a bound PDF but a stable public direct link wasn't confirmed — check lhsaa.org for the current Constitution & Bylaws PDF. Bulletins exist per-sport rather than one consolidated page.",
  },
  {
    state_code: "me",
    state_name: "Maine",
    association_name: "Maine Principals' Association (MPA)",
    handbook_url: "https://mpaprof.org/wp-content/uploads/2025/07/MPA-Handbook.pdf",
    bulletins_url: null,
    eligibility_contact_name: "Michael G. Bisson, Assistant Executive Director",
    eligibility_contact_phone: "(207) 622-0217 ext. 141",
    eligibility_contact_email: "mbisson@mpa.cc",
    notes: "MPA governs all interscholastic activities, not sports-only. Amendments appear incorporated into the annually reissued Handbook rather than a separate bulletins page.",
  },
  {
    state_code: "md",
    state_name: "Maryland",
    association_name: "Maryland Public Secondary Schools Athletic Association (MPSSAA)",
    handbook_url: "https://www.mpssaa.org/wp-content/uploads/2026/03/MPSSAA_Handbook_2526.pdf",
    bulletins_url: "https://www.mpssaa.org/assets/1/6/Fall_Bulletin_2025.pdf",
    eligibility_contact_name: "MPSSAA Office",
    eligibility_contact_phone: "(410) 767-0555",
    eligibility_contact_email: null,
    notes: "MPSSAA's contact pages blocked automated fetching; a named eligibility contact surfaced by search could not be corroborated against the actual page, so it was excluded rather than risk a fabricated name. MPSSAA operates under the MD Dept of Education.",
  },
  {
    state_code: "ma",
    state_name: "Massachusetts",
    association_name: "Massachusetts Interscholastic Athletic Association (MIAA)",
    handbook_url: "https://www.miaa.net/sites/default/files/2025-06/miaa-handbook-25-27.pdf",
    bulletins_url: "https://www.miaa.net/sites/default/files/2026-05/rule-clarification-2025-27.pdf",
    eligibility_contact_name: "MIAA Main Office",
    eligibility_contact_phone: "508-541-7997",
    eligibility_contact_email: "miaa@miaa.net",
    notes: "No dedicated eligibility-specific staff contact found; general office routes inquiries. Bulletins URL points to MIAA's 'Rule Clarification' document.",
  },
  {
    state_code: "mi",
    state_name: "Michigan",
    association_name: "Michigan High School Athletic Association (MHSAA)",
    handbook_url: "https://www.mhsaa.com/about/general-resources",
    bulletins_url: "https://www.mhsaa.com/live/publications",
    eligibility_contact_name: "MHSAA Main Office",
    eligibility_contact_phone: "517-332-5046",
    eligibility_contact_email: "info@mhsaa.com",
    notes: "Could not confirm a direct PDF link to the current Handbook itself — handbook_url points to the General Resources hub where it's likely linked. Bulletins_url points to 'Publications' (Benchmarks, successor to the MHSAA Bulletin).",
  },
  {
    state_code: "mn",
    state_name: "Minnesota",
    association_name: "Minnesota State High School League (MSHSL)",
    handbook_url: "https://www.mshsl.org/mshsl-handbook-governance-documents",
    bulletins_url: "https://www.mshsl.org/eligibility-resources",
    eligibility_contact_name: "MSHSL Main Office",
    eligibility_contact_phone: "763-560-2262",
    eligibility_contact_email: null,
    notes: "MSHSL's guidance is that eligibility questions should come from the school's activities administrator directly to League staff. Site returned 403 on direct fetch during research; individual staff contacts not confirmed.",
  },
  {
    state_code: "ms",
    state_name: "Mississippi",
    association_name: "Mississippi High School Activities Association (MHSAA)",
    handbook_url: "https://www.misshsaa.com/wp-content/uploads/2025/06/2025-26-MHSAA-Handbook-Final-v4.pdf",
    bulletins_url: null,
    eligibility_contact_name: "Tim Shramek, Assistant Director (Eligibility)",
    eligibility_contact_phone: "601-926-4522",
    eligibility_contact_email: "tshramek@misshsaa.com",
    notes: "Listed on the MHSAA staff page as responsible for eligibility. No separate bulletins page apart from the handbook.",
  },
  {
    state_code: "mo",
    state_name: "Missouri",
    association_name: "Missouri State High School Activities Association (MSHSAA)",
    handbook_url: "https://www.mshsaa.org/resources/pdf/Official%20Handbook.pdf",
    bulletins_url: null,
    eligibility_contact_name: "MSHSAA Main Office",
    eligibility_contact_phone: "573-875-4880",
    eligibility_contact_email: "email@mshsaa.org",
    notes: "No individually-named eligibility staff contact found on public pages; general office contact per MSHSAA's published Contact page.",
  },
  {
    state_code: "mt",
    state_name: "Montana",
    association_name: "Montana High School Association (MHSA)",
    handbook_url: "https://assets-rst7.rschooltoday.com/rst7files/uploads/sites/152/2025/09/02150033/2025-26-Handbook-1-edited-8-20.pdf",
    bulletins_url: null,
    eligibility_contact_name: "MHSA Main Office",
    eligibility_contact_phone: "406-442-6010",
    eligibility_contact_email: null,
    notes: "No dedicated eligibility staff name or email found.",
  },
  {
    state_code: "ne",
    state_name: "Nebraska",
    association_name: "Nebraska School Activities Association (NSAA)",
    handbook_url: "https://nsaahome.org/constitution-bylaws/",
    bulletins_url: null,
    eligibility_contact_name: "NSAA Main Office",
    eligibility_contact_phone: "402-489-0386",
    eligibility_contact_email: null,
    notes: "Staff page lists several Assistant Directors but no confirmed eligibility-specific contact with verified email.",
  },
  {
    state_code: "nv",
    state_name: "Nevada",
    association_name: "Nevada Interscholastic Activities Association (NIAA)",
    handbook_url: "https://www.niaa.com/information/about",
    bulletins_url: null,
    eligibility_contact_name: "Cate Sgroi, Assistant Director of Student Eligibility and Compliance",
    eligibility_contact_phone: "775-453-1012",
    eligibility_contact_email: "csgroi@niaa.com",
    notes: "Could not confirm a direct handbook/bylaws PDF link (site returned 403 on direct fetch); handbook_url points to NIAA's general About page.",
  },
  {
    state_code: "nh",
    state_name: "New Hampshire",
    association_name: "New Hampshire Interscholastic Athletic Association (NHIAA)",
    handbook_url: "https://www.nhiaa.org/about-nhiaa/handbook",
    bulletins_url: null,
    eligibility_contact_name: "NHIAA Main Office",
    eligibility_contact_phone: "603-228-8671",
    eligibility_contact_email: null,
    notes: "NHIAA's published policy is that it will not answer specific eligibility questions via email — routes to the local school principal/AD or phone during office hours. Handbook is split into ~40 separate PDFs rather than one file.",
  },
  {
    state_code: "nj",
    state_name: "New Jersey",
    association_name: "New Jersey State Interscholastic Athletic Association (NJSIAA)",
    handbook_url: "https://www.njsiaa.org/sites/default/files/documents/2023-07/NJSIAA%20Constitution%20'23-'24.pdf",
    bulletins_url: null,
    eligibility_contact_name: "Paul Popadiuk, Chief Compliance Officer",
    eligibility_contact_phone: "609-259-2776",
    eligibility_contact_email: "ppopadiuk@njsiaa.org",
    notes: "Constitution PDF found dates to '23-'24 — a more current edition may exist; also see njsiaa.org/schools/student-eligibility. Phone is the general office line.",
  },
  {
    state_code: "nm",
    state_name: "New Mexico",
    association_name: "New Mexico Activities Association (NMAA)",
    handbook_url: "https://www.nmact.org/nmaa-handbook/",
    bulletins_url: null,
    eligibility_contact_name: "NMAA Main Office",
    eligibility_contact_phone: "(505) 923-3110",
    eligibility_contact_email: "feedback@nmact.org",
    notes: "No dedicated eligibility department contact; Handbook page links Section VI (Eligibility Bylaws) as its own PDF.",
  },
  {
    state_code: "ny",
    state_name: "New York",
    association_name: "New York State Public High School Athletic Association (NYSPHSAA)",
    handbook_url: "https://s3.amazonaws.com/nysphsaa.org/documents/2023/8/21/NYSPHSAA_Handbook_Aug_2025.pdf",
    bulletins_url: null,
    eligibility_contact_name: "Todd Nelson, Assistant Director (eligibility interpretations)",
    eligibility_contact_phone: "(518) 690-0771 ext. 309",
    eligibility_contact_email: null,
    notes: "Main contact pages 404'd during verification; phone/title sourced from the staff directory. No email confirmed for Todd Nelson specifically.",
  },
  {
    state_code: "nc",
    state_name: "North Carolina",
    association_name: "North Carolina High School Athletic Association (NCHSAA)",
    handbook_url: "https://www.nchsaa.org/handbook/",
    bulletins_url: "https://www.nchsaa.org/tags/eligibility",
    eligibility_contact_name: "Rhonda Barnwell, Assistant Commissioner, Sports and Championships",
    eligibility_contact_phone: "(919) 240-7373",
    eligibility_contact_email: "rhonda@nchsaa.org",
    notes: "General office: (919) 240-7401 / info@nchsaa.org. No standalone bulletins page found; the eligibility tag page aggregates related content.",
  },
  {
    state_code: "nd",
    state_name: "North Dakota",
    association_name: "North Dakota High School Activities Association (NDHSAA)",
    handbook_url: "https://ndhsaa.com/constitution",
    bulletins_url: null,
    eligibility_contact_name: "NDHSAA Main Office (Matthew Fetsch, Executive Director)",
    eligibility_contact_phone: "(701) 845-3953",
    eligibility_contact_email: "ndhsaa@ndhsaa.org",
    notes: "Directs eligibility questions to the member school's principal/administrator first, not a dedicated eligibility office. Contact page returned 403 during direct verification.",
  },
  {
    state_code: "oh",
    state_name: "Ohio",
    association_name: "Ohio High School Athletic Association (OHSAA)",
    handbook_url: "https://ohsaaweb.blob.core.windows.net/files/SchoolResources/Handbook.pdf",
    bulletins_url: "https://www.ohsaa.org/School-Resources/MondayMinute",
    eligibility_contact_name: "OHSAA Eligibility Staff (Debbie Moore, Roxanne Price, Kristin Ronai)",
    eligibility_contact_phone: "(614) 267-2502",
    eligibility_contact_email: null,
    notes: "OHSAA policy directs eligibility questions to the school's athletic administrator first. No single dedicated eligibility email found. Separate Bylaws doc at ohsaaweb.blob.core.windows.net/files/About-the-OHSAA/Bylaws.pdf.",
  },
  {
    state_code: "ok",
    state_name: "Oklahoma",
    association_name: "Oklahoma Secondary School Activities Association (OSSAA)",
    handbook_url: "https://ossaaillustrated.com/eligibility/",
    bulletins_url: null,
    eligibility_contact_name: "OSSAA Main Office",
    eligibility_contact_phone: "(405) 840-1116",
    eligibility_contact_email: "info@ossaa.com",
    notes: "Could not confirm a stable direct PDF link to the current Administrator's Handbook; linked the official eligibility resource page instead. Routes eligibility questions through the local school's designated administrator.",
  },
  {
    state_code: "or",
    state_name: "Oregon",
    association_name: "Oregon School Activities Association (OSAA)",
    handbook_url: "https://www.osaa.org/docs/handbooks/osaahandbook.pdf",
    bulletins_url: "https://www.osaa.org/governance",
    eligibility_contact_name: "Peter Weber, Executive Director",
    eligibility_contact_phone: "(503) 682-6722 ext. 231",
    eligibility_contact_email: "peterw@osaa.org",
    notes: "General office: (503) 682-6722 / info@osaa.org. Executive Board Policies and Interpretations live under Governance rather than a standalone bulletins page.",
  },
  {
    state_code: "pa",
    state_name: "Pennsylvania",
    association_name: "Pennsylvania Interscholastic Athletic Association (PIAA)",
    handbook_url: "https://www.piaa.org/assets/web/documents/Handbook%20-%20Section%20I%20-%20Constitution%20and%20By-laws.pdf",
    bulletins_url: null,
    eligibility_contact_name: "PIAA Main Office",
    eligibility_contact_phone: "(717) 697-0374",
    eligibility_contact_email: null,
    notes: "PIAA channels contact through a web form rather than a public email. Toll-free (800) 382-1392. Eligibility Rules page: piaa.org/schools/eligibility/default.aspx.",
  },
  {
    state_code: "ri",
    state_name: "Rhode Island",
    association_name: "Rhode Island Interscholastic League (RIIL)",
    handbook_url: "https://www.riil.org/",
    bulletins_url: null,
    eligibility_contact_name: "RIIL Main Office",
    eligibility_contact_phone: "(401) 272-9844",
    eligibility_contact_email: "info@riil.org",
    notes: "Direct Rules & Regulations PDFs are hosted on a document server that may require login — navigate from riil.org for the current handbook. Eligibility waiver requests go through the Executive Director's office.",
  },
  {
    state_code: "sc",
    state_name: "South Carolina",
    association_name: "South Carolina High School League (SCHSL)",
    handbook_url: "https://schsl.org/archives/category/ad-notebook/handbook",
    bulletins_url: "https://schsl.org/archives/19007",
    eligibility_contact_name: "SCHSL Main Office",
    eligibility_contact_phone: "803-798-0120",
    eligibility_contact_email: "cindy-re@schsl.org",
    notes: "No dedicated eligibility department separate from the general office. Bulletins URL points to the current Rules & Regulations archive.",
  },
  {
    state_code: "sd",
    state_name: "South Dakota",
    association_name: "South Dakota High School Activities Association (SDHSAA)",
    handbook_url: "https://sdhsaa.com/athletic-handbook/",
    bulletins_url: "https://sdhsaa.com/board/",
    eligibility_contact_name: "SDHSAA Office",
    eligibility_contact_phone: "605-224-9261",
    eligibility_contact_email: null,
    notes: "No dedicated eligibility staff or email found. Board of Directors meeting minutes are the closest equivalent to bulletins.",
  },
  {
    state_code: "tn",
    state_name: "Tennessee",
    association_name: "Tennessee Secondary School Athletic Association (TSSAA)",
    handbook_url: "https://tssaa.org/tssaa-constitution-and-bylaws",
    bulletins_url: "https://tssaa.org/board-and-council-minutes",
    eligibility_contact_name: "Lauren Jones, Director of Eligibility",
    eligibility_contact_phone: "615-889-6740",
    eligibility_contact_email: "ljones@tssaa.org",
    notes: "Confirmed via the TSSAA staff directory. Other eligibility-related staff: Joe Blair (jblair@tssaa.org).",
  },
  {
    state_code: "tx",
    state_name: "Texas",
    association_name: "University Interscholastic League (UIL)",
    handbook_url: "https://www.uiltexas.org/policy/eligibility",
    bulletins_url: "https://www.uiltexas.org/policy/legislative-council",
    eligibility_contact_name: "Dr. Mark Cousins, Director of Eligibility and Education",
    eligibility_contact_phone: "512-471-5883",
    eligibility_contact_email: null,
    notes: "UIL's contact page uses a JS-obscured email that couldn't be confirmed reliably; secondary sources gave differing addresses (info@uiltexas.org, policy@uiltexas.org) not independently verified.",
  },
  {
    state_code: "ut",
    state_name: "Utah",
    association_name: "Utah High School Activities Association (UHSAA)",
    handbook_url: "https://uhsaa.org/Publications/Handbook/Handbook.pdf",
    bulletins_url: "https://www.uhsaa.org/bot/",
    eligibility_contact_name: "Chris Shipman, Assistant Director (Eligibility Administration)",
    eligibility_contact_phone: "(801) 566-0681",
    eligibility_contact_email: "cshipman@uhsaa.org",
    notes: "UHSAA guidance is to route eligibility questions through the school AD/principal first. Jeff Cluff (jeffcluff@uhsaa.org) also handles compliance/eligibility.",
  },
  {
    state_code: "vt",
    state_name: "Vermont",
    association_name: "Vermont Principals' Association (VPA)",
    handbook_url: "https://vpaonline.org/athletics/",
    bulletins_url: "https://vpaonline.org/about/bylaws/",
    eligibility_contact_name: "VPA General Office",
    eligibility_contact_phone: "(802) 229-0547",
    eligibility_contact_email: "contact@vpaonline.org",
    notes: "No dedicated eligibility-specific contact found. Athletics rules distributed via a separate rulebook order page rather than one handbook PDF.",
  },
  {
    state_code: "va",
    state_name: "Virginia",
    association_name: "Virginia High School League (VHSL)",
    handbook_url: "https://www.vhsl.org/eligibility/vhsl-handbook/",
    bulletins_url: "https://www.vhsl.org/contact-us/",
    eligibility_contact_name: "VHSL Office",
    eligibility_contact_phone: "(434) 977-8475",
    eligibility_contact_email: null,
    notes: "Could not confirm a dedicated eligibility staff email — contact page fetch was incomplete. Executive Committee minutes are published via BoardDocs; no single stable bulletins URL confirmed.",
  },
  {
    state_code: "wa",
    state_name: "Washington",
    association_name: "Washington Interscholastic Activities Association (WIAA)",
    handbook_url: "https://www.wiaa.com/category/handbook/",
    bulletins_url: "https://www.wiaa.com/wiaa-announces-35-proposed-amendments-for-2026-representative-assembly/",
    eligibility_contact_name: "Jeff Lowell, Assistant Executive Director - Compliance & Member Engagement",
    eligibility_contact_phone: "(425) 687-8585",
    eligibility_contact_email: "jlowell@wiaa.com",
    notes: "WIAA advises working through the building administrator first for eligibility questions. No stable standalone bulletins page separate from amendment press releases.",
  },
  {
    state_code: "wv",
    state_name: "West Virginia",
    association_name: "West Virginia Secondary School Activities Commission (WVSSAC)",
    handbook_url: "https://www.wvssac.org/rules-regulations/",
    bulletins_url: "https://www.wvssac.org/rules-regulations/",
    eligibility_contact_name: "Jason Bankston, Director of Compliance",
    eligibility_contact_phone: "304-485-5494",
    eligibility_contact_email: "jason.bankston@wvssac.org",
    notes: "Directs eligibility questions to be routed through the member school's administrator first. Proposed rule changes are published as addenda within the Rules & Regulations page.",
  },
  {
    state_code: "wi",
    state_name: "Wisconsin",
    association_name: "Wisconsin Interscholastic Athletic Association (WIAA)",
    handbook_url: "https://www.wiaawi.org/Portals/0/PDF/Publications/2026-27handbook.pdf",
    bulletins_url: "https://www.wiaawi.org/Portals/0/PDF/Eligibility/Athletic%20Eligibility%20Information%20Bulletin%2026-27.pdf",
    eligibility_contact_name: "Mel Dow, Associate Director (Eligibility)",
    eligibility_contact_phone: "(715) 344-8580",
    eligibility_contact_email: null,
    notes: "WIAA's own guidance directs eligibility questions to the school's principal/AD. Mel Dow's email could not be verified against an official WIAA page.",
  },
  {
    state_code: "wy",
    state_name: "Wyoming",
    association_name: "Wyoming High School Activities Association (WHSAA)",
    handbook_url: "https://www.whsaa.org/whsaa/handbook.pdf",
    bulletins_url: "https://www.whsaa.org/whsaa/boardminutes/",
    eligibility_contact_name: "WHSAA Office",
    eligibility_contact_phone: "(307) 577-0614",
    eligibility_contact_email: "smccash@whsaa.org",
    notes: "General office contact confirmed via multiple sources; no eligibility-specific title/email distinct from the general office found.",
  },

  // National college governing bodies — same config/watched-URL/citation
  // pipeline as the 50 state associations above; `state_code` is just a
  // free-text key, nothing here enforces a 2-letter US state format.
  {
    state_code: "ncaa-d1",
    level: "college",
    state_name: "NCAA Division I",
    association_name: "National Collegiate Athletic Association (NCAA) — Division I",
    handbook_url: "https://ncaapublications.com/products/2025-2026-ncaa-division-i-manual",
    bulletins_url: "https://web3.ncaa.org/lsdbi/",
    eligibility_contact_name: "NCAA Eligibility Center Customer Service",
    eligibility_contact_phone: "877-544-2950",
    eligibility_contact_email: null,
    notes: "No stable direct PDF link — NCAA discontinued print and now generates the full Manual PDF per-user from LSDBi (Legislative Services Database), which requires an NCAA institutional login. handbook_url is the official NCAA Publications landing page instead; someone with LSDBi access will need to pull the actual PDF for /admin/documents upload. 2025-26 edition is current as of this research.",
  },
  {
    state_code: "ncaa-d2",
    level: "college",
    state_name: "NCAA Division II",
    association_name: "National Collegiate Athletic Association (NCAA) — Division II",
    handbook_url: "https://ncaapublications.com/products/2025-2026-ncaa-division-ii-manual",
    bulletins_url: "https://web3.ncaa.org/lsdbi/",
    eligibility_contact_name: "NCAA Eligibility Center Customer Service",
    eligibility_contact_phone: "877-544-2950",
    eligibility_contact_email: null,
    notes: "Same caveat as Division I: no stable direct PDF, full Manual pulled per-user from LSDBi (institutional login required). handbook_url is the NCAA Publications landing page. 2025-26 edition current.",
  },
  {
    state_code: "ncaa-d3",
    level: "college",
    state_name: "NCAA Division III",
    association_name: "National Collegiate Athletic Association (NCAA) — Division III",
    handbook_url: "https://ncaapublications.com/products/2025-2026-ncaa-division-iii-manual",
    bulletins_url: "https://web3.ncaa.org/lsdbi/",
    eligibility_contact_name: "NCAA Eligibility Center Customer Service",
    eligibility_contact_phone: "877-544-2950",
    eligibility_contact_email: null,
    notes: "Same caveat as Division I/II: no stable direct PDF, full Manual pulled per-user from LSDBi (institutional login required). handbook_url is the NCAA Publications landing page. 2025-26 edition current.",
  },
  {
    state_code: "naia",
    level: "college",
    state_name: "NAIA",
    association_name: "National Association of Intercollegiate Athletics (NAIA)",
    handbook_url: "https://www.naia.org/wp-content/uploads/2026/06/2025_Official_Handbook.pdf",
    bulletins_url: "https://interpretations.naia.org/naia-bylaws-policies-and-sport-rules/",
    eligibility_contact_name: "NAIA Eligibility Center",
    eligibility_contact_phone: "816-595-8300",
    eligibility_contact_email: "ECinfo@naia.org",
    notes: "handbook_url is a direct PDF (2025-26 NAIA Official & Policy Handbook — constitution, bylaws, casebook). bulletins_url is 'The Attic,' NAIA's repository of bylaw interpretations. A separate legislative/rules hotline (816-595-8180) and InCred compliance line (Incred@naia.org, 816-595-8390) also exist for narrower questions. Contact info sourced from secondary search results (naia.org/about/contact/ blocked direct fetch) — moderate confidence, worth a spot-check.",
  },
  {
    state_code: "njcaa",
    level: "college",
    state_name: "NJCAA",
    association_name: "National Junior College Athletic Association (NJCAA)",
    handbook_url: "https://www.njcaa.org/member_colleges/handbook",
    bulletins_url: "https://www.njcaa.org/eligibility/compliance-corner",
    eligibility_contact_name: "NJCAA National Office — Compliance",
    eligibility_contact_phone: "719-590-9788",
    eligibility_contact_email: "compliance@njcaa.org",
    notes: "No stable direct PDF for the current Handbook & Casebook — njcaa.org serves it dynamically from this landing page rather than a fixed file URL, so someone will need to pull the current PDF manually for /admin/documents upload. Compliance Corner is NJCAA's eligibility rule-update page. Phone/email verified via multiple independent sources but the official contact page itself couldn't be directly fetched — moderate confidence.",
  },
];
