/* ============================================================
   STATE GUIDES — data for /states and /states/[slug].
   Agency URLs point to official state agency domains only.
   Where a deep link couldn't be verified, we link a verified
   section page (or the homepage) instead of guessing.
============================================================ */

export const STATES = {
  colorado: {
    name: "Colorado",
    abbr: "CO",
    publicLandActs: "23M+ acres of public land — USFS, BLM, and state trust",
    agencies: [
      { label: "Colorado Parks & Wildlife", url: "https://cpw.state.co.us" },
      { label: "Hunting Regulations & Brochures", url: "https://cpw.state.co.us/hunting" },
      { label: "Buy a License (CPW Shop)", url: "https://www.cpwshop.com" },
      { label: "Big Game Draw & Applications", url: "https://cpw.state.co.us/hunting/big-game" },
    ],
    outlierTake: [
      "Colorado runs most of its big game licenses through an annual draw. You apply in the spring for the licenses you want in the fall, and the draw uses a preference point system — miss out on a license, earn a point, and points improve your odds in future years. Some licenses have historically been available over the counter without a draw at all, while the most sought-after hunts can take years of points to pull. Which is which changes over time, so treat the draw-versus-OTC question as something you confirm with CPW every single year, never something you assume.",
      "The state is carved into game management units, and your license is generally tied to specific units. Two units that touch each other on the map can hunt completely differently — different pressure, different access, different animal densities. Unit research is where a Colorado hunt is actually won or lost: study the terrain, the access points, and the harvest data CPW publishes before you commit your points or your season to a unit. A mediocre plan in a well-researched unit beats a great plan in a unit you picked off a rumor.",
      "The public land situation is the good news. Colorado has one of the best public land mixes in the West — enormous stretches of National Forest up high, BLM ground in the lower country, and state trust land scattered through it. Learn the difference, because access rules aren't identical across them, and a good mapping app that shows land ownership boundaries is worth more than most gear you could buy instead.",
      "One thing flatlanders underestimate every year: the altitude. A lot of Colorado's best hunting lives above 9,000 feet, and no amount of sea-level fitness fully spares you from thin air. Build in time to acclimate, hydrate like it's your job, know the early signs of altitude sickness, and plan your first days conservatively. And before any of this becomes a plan: verify every season, deadline, and regulation directly with Colorado Parks & Wildlife — rules change, and the agency is the only source that counts.",
    ],
    camName: "Elk Country",
  },
  wyoming: {
    name: "Wyoming",
    abbr: "WY",
    publicLandActs: "30M+ acres of public land — BLM, USFS, and state sections",
    agencies: [
      { label: "Wyoming Game & Fish Department", url: "https://wgfd.wyo.gov" },
      { label: "Hunting Regulations & Info", url: "https://wgfd.wyo.gov/hunting" },
      { label: "Buy a License", url: "https://wgfd.wyo.gov/apply-or-buy" },
      { label: "Draw Applications & Preference Points", url: "https://wgfd.wyo.gov/apply-or-buy" },
    ],
    outlierTake: null,
    camName: null,
  },
  montana: {
    name: "Montana",
    abbr: "MT",
    publicLandActs: "27M+ acres of public land — USFS, BLM, and state lands",
    agencies: [
      { label: "Montana Fish, Wildlife & Parks", url: "https://fwp.mt.gov" },
      { label: "Hunting Regulations & Seasons", url: "https://fwp.mt.gov/hunt" },
      { label: "Buy a License", url: "https://fwp.mt.gov/buyandapply" },
      { label: "Permit Draws & Applications", url: "https://fwp.mt.gov/buyandapply" },
    ],
    outlierTake: null,
    camName: null,
  },
  idaho: {
    name: "Idaho",
    abbr: "ID",
    publicLandActs: "32M+ acres of public land — the most by share in the lower 48",
    agencies: [
      { label: "Idaho Fish & Game", url: "https://idfg.idaho.gov" },
      { label: "Hunting Seasons & Rules", url: "https://idfg.idaho.gov/hunt" },
      { label: "Licenses, Tags & Permits", url: "https://idfg.idaho.gov/licenses" },
      { label: "Controlled Hunt Drawings", url: "https://idfg.idaho.gov/hunt" },
    ],
    outlierTake: null,
    camName: null,
  },
  utah: {
    name: "Utah",
    abbr: "UT",
    publicLandActs: "33M+ acres of public land — BLM, USFS, and state trust",
    agencies: [
      { label: "Utah Division of Wildlife Resources", url: "https://wildlife.utah.gov" },
      { label: "Hunting Rules & Guidebooks", url: "https://wildlife.utah.gov/hunting/" },
      { label: "Licenses & Permits", url: "https://wildlife.utah.gov" },
      { label: "Permit Drawings", url: "https://wildlife.utah.gov/hunting/" },
    ],
    outlierTake: null,
    camName: null,
  },
  alabama: {
    name: "Alabama",
    abbr: "AL",
    publicLandActs: "1M+ acres of public land — national forests, WMAs, and state lands",
    agencies: [
      { label: "Alabama Wildlife & Freshwater Fisheries (Outdoor Alabama)", url: "https://www.outdooralabama.com" },
      { label: "Hunting Regulations", url: "https://www.outdooralabama.com" },
      { label: "Licenses & Permits", url: "https://www.outdooralabama.com" },
    ],
    outlierTake: null,
    camName: null,
  },
  alaska: {
    name: "Alaska",
    abbr: "AK",
    publicLandActs: "365M+ acres of public land — the most of any state, mostly federal",
    agencies: [
      { label: "Alaska Department of Fish and Game", url: "https://www.adfg.alaska.gov" },
      { label: "Hunting Regulations", url: "https://www.adfg.alaska.gov/index.cfm?adfg=regulations.main" },
      { label: "Licenses & Permits", url: "https://www.adfg.alaska.gov/index.cfm?adfg=license.main" },
    ],
    outlierTake: null,
    camName: null,
  },
  arizona: {
    name: "Arizona",
    abbr: "AZ",
    publicLandActs: "38M+ acres of public land — USFS, BLM, state trust, and tribal",
    agencies: [
      { label: "Arizona Game and Fish Department", url: "https://www.azgfd.com" },
      { label: "Hunting Regulations", url: "https://www.azgfd.com" },
      { label: "Licenses & Permits", url: "https://www.azgfd.com" },
    ],
    outlierTake: null,
    camName: null,
  },
  arkansas: {
    name: "Arkansas",
    abbr: "AR",
    publicLandActs: "3M+ acres of public land — national forests and WMAs",
    agencies: [
      { label: "Arkansas Game and Fish Commission", url: "https://www.agfc.com" },
      { label: "Hunting Regulations", url: "https://www.agfc.com" },
      { label: "Licenses & Permits", url: "https://licensing.agfc.com" },
    ],
    outlierTake: null,
    camName: null,
  },
  california: {
    name: "California",
    abbr: "CA",
    publicLandActs: "45M+ acres of public land — national forests, BLM, and state land",
    agencies: [
      { label: "California Department of Fish and Wildlife", url: "https://wildlife.ca.gov" },
      { label: "Hunting Regulations", url: "https://wildlife.ca.gov/Hunting/Regulations" },
      { label: "Licenses & Permits", url: "https://wildlife.ca.gov/Licensing/Hunting" },
    ],
    outlierTake: null,
    camName: null,
  },
  connecticut: {
    name: "Connecticut",
    abbr: "CT",
    publicLandActs: "State forests, WMAs, and land trust preserves",
    agencies: [
      { label: "CT DEEP Wildlife Division", url: "https://portal.ct.gov/DEEP/Wildlife" },
      { label: "Hunting Regulations", url: "https://portal.ct.gov/DEEP/Hunting/CT-Hunting-and-Trapping" },
      { label: "Licenses & Permits", url: "https://portal.ct.gov/DEEP/Wildlife" },
    ],
    outlierTake: null,
    camName: null,
  },
  delaware: {
    name: "Delaware",
    abbr: "DE",
    publicLandActs: "Wildlife areas and state forests — small but accessible",
    agencies: [
      { label: "Delaware Division of Fish and Wildlife", url: "https://dnrec.delaware.gov/fish-wildlife/" },
      { label: "Hunting Regulations", url: "https://dnrec.delaware.gov/fish-wildlife/" },
      { label: "Licenses & Permits", url: "https://dnrec.delaware.gov/fish-wildlife/licenses-registrations/" },
    ],
    outlierTake: null,
    camName: null,
  },
  florida: {
    name: "Florida",
    abbr: "FL",
    publicLandActs: "10M+ acres of public land — WMAs, state forests, and national forests",
    agencies: [
      { label: "Florida Fish and Wildlife Conservation Commission", url: "https://myfwc.com" },
      { label: "Hunting Regulations", url: "https://myfwc.com" },
      { label: "Licenses & Permits", url: "https://myfwc.com/license/" },
    ],
    outlierTake: null,
    camName: null,
  },
  georgia: {
    name: "Georgia",
    abbr: "GA",
    publicLandActs: "WMAs, national forests, and state parks across the state",
    agencies: [
      { label: "Georgia Wildlife Resources Division", url: "https://georgiawildlife.com" },
      { label: "Hunting Regulations", url: "https://georgiawildlife.com/hunting/hunter-resources" },
      { label: "Licenses & Permits", url: "https://georgiawildlife.com" },
    ],
    outlierTake: null,
    camName: null,
  },
  hawaii: {
    name: "Hawaii",
    abbr: "HI",
    publicLandActs: "Forest reserves and public hunting units on state land",
    agencies: [
      { label: "Hawaii Division of Forestry & Wildlife (DLNR)", url: "https://dlnr.hawaii.gov/dofaw/" },
      { label: "Hunting Regulations", url: "https://dlnr.hawaii.gov/dofaw/" },
      { label: "Licenses & Permits", url: "https://dlnr.hawaii.gov/dofaw/" },
    ],
    outlierTake: null,
    camName: null,
  },
  illinois: {
    name: "Illinois",
    abbr: "IL",
    publicLandActs: "State-owned sites and WMAs — a patchwork amid private farmland",
    agencies: [
      { label: "Illinois Department of Natural Resources", url: "https://dnr.illinois.gov" },
      { label: "Hunting Regulations", url: "https://dnr.illinois.gov/hunting.html" },
      { label: "Licenses & Permits", url: "https://dnr.illinois.gov/lpr/huntinglicensesfees.html" },
    ],
    outlierTake: null,
    camName: null,
  },
  indiana: {
    name: "Indiana",
    abbr: "IN",
    publicLandActs: "State forests, fish & wildlife areas, and public hunting land",
    agencies: [
      { label: "Indiana DNR Fish & Wildlife", url: "https://www.in.gov/dnr/fish-and-wildlife/" },
      { label: "Hunting Regulations", url: "https://www.in.gov/dnr/fish-and-wildlife/hunting-and-trapping/" },
      { label: "Licenses & Permits", url: "https://www.in.gov/dnr/fish-and-wildlife/" },
    ],
    outlierTake: null,
    camName: null,
  },
  iowa: {
    name: "Iowa",
    abbr: "IA",
    publicLandActs: "Wildlife management areas and public hunting atlas land",
    agencies: [
      { label: "Iowa Department of Natural Resources", url: "https://www.iowadnr.gov" },
      { label: "Hunting Regulations", url: "https://www.iowadnr.gov/things-do/hunting-trapping/hunting-regulations-laws" },
      { label: "Licenses & Permits", url: "https://www.iowadnr.gov/things-do/hunting-trapping" },
    ],
    outlierTake: null,
    camName: null,
  },
  kansas: {
    name: "Kansas",
    abbr: "KS",
    publicLandActs: "Walk-In Hunting Access land plus state wildlife areas",
    agencies: [
      { label: "Kansas Department of Wildlife & Parks", url: "https://www.ksoutdoors.gov" },
      { label: "Hunting Regulations", url: "https://www.ksoutdoors.gov" },
      { label: "Licenses & Permits", url: "https://programs.ksoutdoors.com" },
    ],
    outlierTake: null,
    camName: null,
  },
  kentucky: {
    name: "Kentucky",
    abbr: "KY",
    publicLandActs: "WMAs and national forest land, concentrated in the east",
    agencies: [
      { label: "Kentucky Department of Fish & Wildlife Resources", url: "https://fw.ky.gov" },
      { label: "Hunting Regulations", url: "https://fw.ky.gov/Hunt/Pages/default.aspx" },
      { label: "Licenses & Permits", url: "https://fw.ky.gov" },
    ],
    outlierTake: null,
    camName: null,
  },
  louisiana: {
    name: "Louisiana",
    abbr: "LA",
    publicLandActs: "1.5M+ acres of public land — WMAs and national forest",
    agencies: [
      { label: "Louisiana Department of Wildlife and Fisheries", url: "https://www.wlf.louisiana.gov" },
      { label: "Hunting Regulations", url: "https://www.wlf.louisiana.gov" },
      { label: "Licenses & Permits", url: "https://www.wlf.louisiana.gov" },
    ],
    outlierTake: null,
    camName: null,
  },
  maine: {
    name: "Maine",
    abbr: "ME",
    publicLandActs: "Public reserved lands plus vast easement-access timberland",
    agencies: [
      { label: "Maine Department of Inland Fisheries & Wildlife", url: "https://www.maine.gov/ifw/" },
      { label: "Hunting Regulations", url: "https://www.maine.gov/ifw/" },
      { label: "Licenses & Permits", url: "https://www.maine.gov/ifw/" },
    ],
    outlierTake: null,
    camName: null,
  },
  maryland: {
    name: "Maryland",
    abbr: "MD",
    publicLandActs: "State forests and WMAs across the Chesapeake region",
    agencies: [
      { label: "Maryland Department of Natural Resources", url: "https://dnr.maryland.gov" },
      { label: "Hunting Regulations", url: "https://dnr.maryland.gov" },
      { label: "Licenses & Permits", url: "https://dnr.maryland.gov" },
    ],
    outlierTake: null,
    camName: null,
  },
  massachusetts: {
    name: "Massachusetts",
    abbr: "MA",
    publicLandActs: "State forests, WMAs, and MassWildlife land",
    agencies: [
      { label: "MassWildlife (Division of Fisheries & Wildlife)", url: "https://www.mass.gov/orgs/division-of-fisheries-and-wildlife" },
      { label: "Hunting Regulations", url: "https://www.mass.gov/orgs/division-of-fisheries-and-wildlife" },
      { label: "Licenses & Permits", url: "https://www.mass.gov/orgs/division-of-fisheries-and-wildlife" },
    ],
    outlierTake: null,
    camName: null,
  },
  michigan: {
    name: "Michigan",
    abbr: "MI",
    publicLandActs: "4M+ acres of state forest land, plus national forest",
    agencies: [
      { label: "Michigan DNR", url: "https://www.michigan.gov/dnr" },
      { label: "Hunting Regulations", url: "https://www.michigan.gov/dnr/things-to-do/hunting" },
      { label: "Licenses & Permits", url: "https://www.michigan.gov/dnr/buy-and-apply" },
    ],
    outlierTake: null,
    camName: null,
  },
  minnesota: {
    name: "Minnesota",
    abbr: "MN",
    publicLandActs: "Wildlife management areas and extensive state and national forest",
    agencies: [
      { label: "Minnesota DNR", url: "https://www.dnr.state.mn.us" },
      { label: "Hunting Regulations", url: "https://www.dnr.state.mn.us/regulations/hunting/index.html" },
      { label: "Licenses & Permits", url: "https://www.dnr.state.mn.us" },
    ],
    outlierTake: null,
    camName: null,
  },
  mississippi: {
    name: "Mississippi",
    abbr: "MS",
    publicLandActs: "WMAs and national forest land across the state",
    agencies: [
      { label: "Mississippi Dept. of Wildlife, Fisheries & Parks", url: "https://www.mdwfp.com" },
      { label: "Hunting Regulations", url: "https://www.mdwfp.com" },
      { label: "Licenses & Permits", url: "https://www.mdwfp.com" },
    ],
    outlierTake: null,
    camName: null,
  },
  missouri: {
    name: "Missouri",
    abbr: "MO",
    publicLandActs: "1M+ acres of conservation areas managed by MDC",
    agencies: [
      { label: "Missouri Department of Conservation", url: "https://mdc.mo.gov" },
      { label: "Hunting Regulations", url: "https://mdc.mo.gov" },
      { label: "Licenses & Permits", url: "https://mdc.mo.gov" },
    ],
    outlierTake: null,
    camName: null,
  },
  nebraska: {
    name: "Nebraska",
    abbr: "NE",
    publicLandActs: "Wildlife management areas and public access land",
    agencies: [
      { label: "Nebraska Game and Parks Commission", url: "https://outdoornebraska.gov" },
      { label: "Hunting Regulations", url: "https://outdoornebraska.gov" },
      { label: "Licenses & Permits", url: "https://www.gooutdoorsne.com" },
    ],
    outlierTake: null,
    camName: null,
  },
  nevada: {
    name: "Nevada",
    abbr: "NV",
    publicLandActs: "80%+ federal land — BLM and USFS dominate the state",
    agencies: [
      { label: "Nevada Department of Wildlife", url: "https://www.ndow.org" },
      { label: "Hunting Regulations", url: "https://www.ndow.org" },
      { label: "Licenses & Permits", url: "https://www.ndow.org" },
    ],
    outlierTake: null,
    camName: null,
  },
  "new-hampshire": {
    name: "New Hampshire",
    abbr: "NH",
    publicLandActs: "State forests and WMAs in the White Mountains region",
    agencies: [
      { label: "New Hampshire Fish and Game Department", url: "https://www.wildlife.nh.gov" },
      { label: "Hunting Regulations", url: "https://www.wildlife.nh.gov" },
      { label: "Licenses & Permits", url: "https://www.wildlife.nh.gov/licenses-and-permits" },
    ],
    outlierTake: null,
    camName: null,
  },
  "new-jersey": {
    name: "New Jersey",
    abbr: "NJ",
    publicLandActs: "Wildlife management areas across a densely populated state",
    agencies: [
      { label: "NJ Division of Fish and Wildlife", url: "https://dep.nj.gov/njfw/" },
      { label: "Hunting Regulations", url: "https://dep.nj.gov/njfw/" },
      { label: "Licenses & Permits", url: "https://dep.nj.gov/njfw/" },
    ],
    outlierTake: null,
    camName: null,
  },
  "new-mexico": {
    name: "New Mexico",
    abbr: "NM",
    publicLandActs: "27M+ acres of public land — BLM, USFS, and state trust",
    agencies: [
      { label: "New Mexico Department of Game & Fish", url: "https://wildlife.dgf.nm.gov" },
      { label: "Hunting Regulations", url: "https://wildlife.dgf.nm.gov" },
      { label: "Licenses & Permits", url: "https://onlinesales.wildlife.state.nm.us" },
    ],
    outlierTake: null,
    camName: null,
  },
  "new-york": {
    name: "New York",
    abbr: "NY",
    publicLandActs: "State forests and WMAs, plus the Adirondack and Catskill Parks",
    agencies: [
      { label: "NY Department of Environmental Conservation", url: "https://dec.ny.gov" },
      { label: "Hunting Regulations", url: "https://dec.ny.gov/things-to-do/hunting" },
      { label: "Licenses & Permits", url: "https://dec.ny.gov/regulatory/permits-licenses/sporting-and-use/sporting/hunting-license" },
    ],
    outlierTake: null,
    camName: null,
  },
  "north-carolina": {
    name: "North Carolina",
    abbr: "NC",
    publicLandActs: "National forests and game lands from mountains to coast",
    agencies: [
      { label: "NC Wildlife Resources Commission", url: "https://www.ncwildlife.gov" },
      { label: "Hunting Regulations", url: "https://www.ncwildlife.gov" },
      { label: "Licenses & Permits", url: "https://www.ncwildlife.gov" },
    ],
    outlierTake: null,
    camName: null,
  },
  "north-dakota": {
    name: "North Dakota",
    abbr: "ND",
    publicLandActs: "PLOTS program access plus state and federal wildlife land",
    agencies: [
      { label: "North Dakota Game and Fish Department", url: "https://gf.nd.gov" },
      { label: "Hunting Regulations", url: "https://gf.nd.gov/hunting" },
      { label: "Licenses & Permits", url: "https://apps.nd.gov/gnf/onlineservices/lic/public/myGNF.htm" },
    ],
    outlierTake: null,
    camName: null,
  },
  ohio: {
    name: "Ohio",
    abbr: "OH",
    publicLandActs: "State wildlife areas and forests across the state",
    agencies: [
      { label: "Ohio DNR Division of Wildlife", url: "https://wildlife.ohiodnr.gov" },
      { label: "Hunting Regulations", url: "https://wildlife.ohiodnr.gov" },
      { label: "Licenses & Permits", url: "https://wildlife.ohiodnr.gov" },
    ],
    outlierTake: null,
    camName: null,
  },
  oklahoma: {
    name: "Oklahoma",
    abbr: "OK",
    publicLandActs: "WMAs and national grasslands open to public hunting",
    agencies: [
      { label: "Oklahoma Department of Wildlife Conservation", url: "https://www.wildlifedepartment.com" },
      { label: "Hunting Regulations", url: "https://www.wildlifedepartment.com/hunting" },
      { label: "Licenses & Permits", url: "https://www.wildlifedepartment.com" },
    ],
    outlierTake: null,
    camName: null,
  },
  oregon: {
    name: "Oregon",
    abbr: "OR",
    publicLandActs: "Large BLM and USFS holdings — public land across most of the state",
    agencies: [
      { label: "Oregon Department of Fish & Wildlife", url: "https://myodfw.com" },
      { label: "Hunting Regulations", url: "https://myodfw.com/articles/oregon-fishing-hunting-regulations-and-updates" },
      { label: "Licenses & Permits", url: "https://myodfw.com" },
    ],
    outlierTake: null,
    camName: null,
  },
  pennsylvania: {
    name: "Pennsylvania",
    abbr: "PA",
    publicLandActs: "1.5M+ acres of State Game Lands — the backbone of PA hunting",
    agencies: [
      { label: "Pennsylvania Game Commission", url: "https://www.pgc.pa.gov" },
      { label: "Hunting Regulations", url: "https://www.pgc.pa.gov" },
      { label: "Licenses & Permits", url: "https://www.pgc.pa.gov" },
    ],
    outlierTake: null,
    camName: null,
  },
  "rhode-island": {
    name: "Rhode Island",
    abbr: "RI",
    publicLandActs: "Management areas and state land — small but well-used",
    agencies: [
      { label: "RI DEM Division of Fish and Wildlife", url: "https://dem.ri.gov/natural-resources-bureau/fish-wildlife" },
      { label: "Hunting Regulations", url: "https://dem.ri.gov/natural-resources-bureau/fish-wildlife" },
      { label: "Licenses & Permits", url: "https://dem.ri.gov/natural-resources-bureau/fish-wildlife" },
    ],
    outlierTake: null,
    camName: null,
  },
  "south-carolina": {
    name: "South Carolina",
    abbr: "SC",
    publicLandActs: "WMAs and national forest land across the state",
    agencies: [
      { label: "South Carolina Department of Natural Resources", url: "https://www.dnr.sc.gov" },
      { label: "Hunting Regulations", url: "https://www.dnr.sc.gov" },
      { label: "Licenses & Permits", url: "https://www.dnr.sc.gov" },
    ],
    outlierTake: null,
    camName: null,
  },
  "south-dakota": {
    name: "South Dakota",
    abbr: "SD",
    publicLandActs: "GFP-managed public hunting land plus national grasslands",
    agencies: [
      { label: "South Dakota Game, Fish and Parks", url: "https://gfp.sd.gov" },
      { label: "Hunting Regulations", url: "https://gfp.sd.gov/regulations/" },
      { label: "Licenses & Permits", url: "https://gfp.sd.gov" },
    ],
    outlierTake: null,
    camName: null,
  },
  tennessee: {
    name: "Tennessee",
    abbr: "TN",
    publicLandActs: "WMAs and national forest land across the state",
    agencies: [
      { label: "Tennessee Wildlife Resources Agency", url: "https://www.tn.gov/twra.html" },
      { label: "Hunting Regulations", url: "https://www.tn.gov/twra.html" },
      { label: "Licenses & Permits", url: "https://www.tn.gov/twra.html" },
    ],
    outlierTake: null,
    camName: null,
  },
  texas: {
    name: "Texas",
    abbr: "TX",
    publicLandActs: "Public hunting land is limited — most hunting is on private land",
    agencies: [
      { label: "Texas Parks and Wildlife Department", url: "https://tpwd.texas.gov" },
      { label: "Hunting Regulations", url: "https://tpwd.texas.gov/regulations/" },
      { label: "Licenses & Permits", url: "https://tpwd.texas.gov/business/licenses/online_sales/" },
    ],
    outlierTake: null,
    camName: null,
  },
  vermont: {
    name: "Vermont",
    abbr: "VT",
    publicLandActs: "State forests, WMAs, and Green Mountain National Forest",
    agencies: [
      { label: "Vermont Fish & Wildlife Department", url: "https://www.vtfishandwildlife.com" },
      { label: "Hunting Regulations", url: "https://www.vtfishandwildlife.com" },
      { label: "Licenses & Permits", url: "https://anrweb.vt.gov/FWD/FW/LicenseInformation.aspx" },
    ],
    outlierTake: null,
    camName: null,
  },
  virginia: {
    name: "Virginia",
    abbr: "VA",
    publicLandActs: "WMAs and national forest land, concentrated west of I-95",
    agencies: [
      { label: "Virginia Department of Wildlife Resources", url: "https://dwr.virginia.gov" },
      { label: "Hunting Regulations", url: "https://dwr.virginia.gov" },
      { label: "Licenses & Permits", url: "https://dwr.virginia.gov" },
    ],
    outlierTake: null,
    camName: null,
  },
  washington: {
    name: "Washington",
    abbr: "WA",
    publicLandActs: "3M+ acres of WDFW wildlife areas plus national forest",
    agencies: [
      { label: "Washington Department of Fish & Wildlife", url: "https://wdfw.wa.gov" },
      { label: "Hunting Regulations", url: "https://wdfw.wa.gov" },
      { label: "Licenses & Permits", url: "https://fishhunt.dfw.wa.gov" },
    ],
    outlierTake: null,
    camName: null,
  },
  "west-virginia": {
    name: "West Virginia",
    abbr: "WV",
    publicLandActs: "1.5M+ acres of public land — national forest and WMAs",
    agencies: [
      { label: "West Virginia Division of Natural Resources", url: "https://wvdnr.gov" },
      { label: "Hunting Regulations", url: "https://wvdnr.gov/hunting/" },
      { label: "Licenses & Permits", url: "https://wvdnr.gov" },
    ],
    outlierTake: null,
    camName: null,
  },
  wisconsin: {
    name: "Wisconsin",
    abbr: "WI",
    publicLandActs: "State and county forest land open to public hunting",
    agencies: [
      { label: "Wisconsin DNR", url: "https://dnr.wisconsin.gov" },
      { label: "Hunting Regulations", url: "https://dnr.wisconsin.gov" },
      { label: "Licenses & Permits", url: "https://gowild.wi.gov" },
    ],
    outlierTake: null,
    camName: null,
  },
};

export function getStateSlugs() {
  return Object.keys(STATES);
}

export function getState(slug) {
  return STATES[slug] || null;
}
